//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTDataSimulationServiceBLL.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemaFile
    {
        public SchemaFile()
        {
            this.SimulatorProcessDetails = new HashSet<SimulatorProcessDetail>();
        }
    
        public decimal SchemaFileID { get; set; }
        public decimal SimulatorID { get; set; }
        public string XSDFile { get; set; }
        public System.DateTime UploadedDate { get; set; }
    
        public virtual Simulator Simulator { get; set; }
        public virtual ICollection<SimulatorProcessDetail> SimulatorProcessDetails { get; set; }
    }
}
