//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTDataSimulationServiceBLL.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulatorProcessDetail
    {
        public decimal SimulatorProcessID { get; set; }
        public decimal SimulatorID { get; set; }
        public decimal SchemaFileID { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool SimulatorProcessStatus { get; set; }
        public bool IsRemoved { get; set; }
        public decimal SizeOfDateReceived { get; set; }
    
        public virtual SchemaFile SchemaFile { get; set; }
        public virtual Simulator Simulator { get; set; }
    }
}
