//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTDataSimulationServiceBLL.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulator
    {
        public Simulator()
        {
            this.SchemaFiles = new HashSet<SchemaFile>();
            this.SimulatorProcessDetails = new HashSet<SimulatorProcessDetail>();
            this.URLDetails = new HashSet<URLDetail>();
        }
    
        public decimal SimulatorID { get; set; }
        public string SimulatorName { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public decimal UserID { get; set; }
    
        public virtual ICollection<SchemaFile> SchemaFiles { get; set; }
        public virtual ICollection<SimulatorProcessDetail> SimulatorProcessDetails { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<URLDetail> URLDetails { get; set; }
    }
}
