//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTDataSimulationServiceBLL.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLDetail
    {
        public decimal URLDetailID { get; set; }
        public decimal SimulatorID { get; set; }
        public string ClassName { get; set; }
        public string PostURL { get; set; }
    
        public virtual Simulator Simulator { get; set; }
    }
}
